### ISSUE TITLE
Videos work in mobile. Videos do not work in browser

### ISSUE THREAD

**Issue by SahBove** [be-ez/blog#27]
The videos are being put in .img tag and not .vid tag.

**Comment by be-ez** [comment]
content types `video/quicktime` and `video/mp4` are now detected and applied the appropriate tag. 
`<video mute autostart loop  \> `

It's possible to use the same injection technique to allow any internal component ( BlogPost, GenericContent Card, etc) to be added inline via RichText in Generic Content. 

This should help close #29 

this was closed in commit 14a2ed7a90da20
